### ISSUE TITLE
create a timeline of offsite team photos

### ISSUE THREAD

**Issue by gbinal** [18F/meta#3]

**Comment by gbinal** [comment]
![p9280044](https://cloud.githubusercontent.com/assets/633088/13960928/a9ebcfe2-f030-11e5-8ce2-ff4e0f48a63c.jpg)
![img_20140709_173255 1](https://cloud.githubusercontent.com/assets/633088/13960929/a9ebf08a-f030-11e5-98f9-3d25681eb830.jpg)
![20150123_152556](https://cloud.githubusercontent.com/assets/633088/13960931/a9edd94a-f030-11e5-9532-a715c3db708e.jpg)
![2014-03-27_offsite_photo](https://cloud.githubusercontent.com/assets/633088/13960930/a9ec2a0a-f030-11e5-8e9b-db2b9157ab42.jpg)

**Comment by mkhandekar** [comment]
I needed these photos this weekend for a thing, and I'm thankful for ya @gbinal for making sure these moments were easy to find.
